@startuml gtlib

skinparam Monochrome true
skinparam linetype ortho
hide circle
hide enum methods
hide enum members
hide class methods
hide class members

class Procedure
class Enumerator
class MaxSearch
class Selection
class SeqInFileEnumerator
class StringStreamEnumerator
class Summation
class LinSearch
class IntervalEnumerator
class ArrayEnumerator
class Counting
class Greater
class Less

MaxSearch -up-|> Procedure
Selection -up-|> Procedure
Summation -up-|> Procedure
LinSearch -up-|> Procedure

SeqInFileEnumerator -up-|> Enumerator
StringStreamEnumerator -down-|> Enumerator
IntervalEnumerator -right-|> Enumerator
ArrayEnumerator -left-|> Enumerator

Counting -up-|> Summation

MaxSearch ..> Greater
MaxSearch .up.> Less

@enduml

@startuml procedure-enumerator-uml

skinparam Monochrome true
hide circle
skinparam ClassAttributeIconSize 0

class Procedure<Item>{
    # enor : Enumerator<Item>*
    + run() : void {final}
    + addEnumerator(Enumerator<Item>*) : void {final}
    # init() : void {virtual}
    # first() : void {virtual}
    # body(Item) : void {virtual}
    # loopCond() : bool {virtual}
    # whileCond(Item) : bool {virtual}
}


interface Enumerator<Item> <<inteface>>{
    + first() : void
    + next() : void
    + current() : Item
    + end() : void
}

@enduml


@startuml procedure-enumerator

skinparam Monochrome true
hide circle
skinparam ClassAttributeIconSize 0

class Procedure{
    run() 
    addEnumerator(Enumerator<Item>) 
}


interface Enumerator{
    first() 
    next() 
    current() 
    end() 
}

@enduml